# Generated by Django 5.0.6 on 2024-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_watchlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='stock_symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
