# Generated by Django 5.0.6 on 2024-05-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_watchlist_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='market_close',
            field=models.CharField(default='16:30', max_length=10),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='market_open',
            field=models.CharField(default='08:00', max_length=10),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='region',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='timezone',
            field=models.CharField(default='UTC+00', max_length=20),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
